// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB31rErkub-_txnCoAMfAnuPQLwkUu6HUQ',
    appId: '1:277699770654:web:e1400a8f606d7537f9f10f',
    messagingSenderId: '277699770654',
    projectId: 'todo-4d54c',
    authDomain: 'todo-4d54c.firebaseapp.com',
    storageBucket: 'todo-4d54c.firebasestorage.app',
    measurementId: 'G-RFQMZSRM9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1ScxXRtoCdjJH1gYRa8h-qShApKNs2w',
    appId: '1:277699770654:android:7df812d2c7c8758ff9f10f',
    messagingSenderId: '277699770654',
    projectId: 'todo-4d54c',
    storageBucket: 'todo-4d54c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ6_aZv1DDcsscejY4o1mhnGNZkj8dUh8',
    appId: '1:277699770654:ios:c6b32f0aa4d677fbf9f10f',
    messagingSenderId: '277699770654',
    projectId: 'todo-4d54c',
    storageBucket: 'todo-4d54c.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ6_aZv1DDcsscejY4o1mhnGNZkj8dUh8',
    appId: '1:277699770654:ios:c6b32f0aa4d677fbf9f10f',
    messagingSenderId: '277699770654',
    projectId: 'todo-4d54c',
    storageBucket: 'todo-4d54c.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB31rErkub-_txnCoAMfAnuPQLwkUu6HUQ',
    appId: '1:277699770654:web:31017b18c73ac3edf9f10f',
    messagingSenderId: '277699770654',
    projectId: 'todo-4d54c',
    authDomain: 'todo-4d54c.firebaseapp.com',
    storageBucket: 'todo-4d54c.firebasestorage.app',
    measurementId: 'G-71XL8FS6T8',
  );
}
